### ISSUE TITLE
Upgrade gcc + cuda versions in Deception build

### ISSUE THREAD

**Issue by jaelynlitz** [eagles-project/mam4xx#368]
Discussed when finding some build issues with haero's cpu build - 

- Deception's build currently uses gcc/10.2.0 + cuda/11.4
- haero's cpu build now requires gcc > 10
- cuda 11.4 isn't compatible with gcc > 10

It is proposed that we upgrade the build to match Perlmutter - gcc/11.2.0 + cuda/11.7. These are both available on Deception.

**Comment by jaelynlitz** [comment]
PM has a100s - it may be beneficial to switch our test pipelines to the a100 partition(s) on Deception. The p100 build of haero works on the a100s (with a warning that using compute capability 6.0 may be less performant since it's a compute capability 8.0 node), but building haero with `Kokkos_ARCH_AMPERE80=ON` results in the following error:

```/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(407): error: identifier "__short2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(409): error: identifier "__ushort2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(411): error: identifier "__int2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(413): error: identifier "__uint2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(415): error: identifier "__ll2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(417): error: identifier "__ull2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(407): error: identifier "__short2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(409): error: identifier "__ushort2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(411): error: identifier "__int2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(413): error: identifier "__uint2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(415): error: identifier "__ll2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(417): error: identifier "__ull2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(407): error: identifier "__short2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(409): error: identifier "__ushort2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(411): error: identifier "__int2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(413): error: identifier "__uint2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(415): error: identifier "__ll2bfloat16_rn" is undefined

/qfs/projects/eagles/litz372/mam4xx/second_new_haero_gpu_double_debug/include/kokkos/Cuda/Kokkos_Cuda_Half_Conversion.hpp(417): error: identifier "__ull2bfloat16_rn" is undefined

6 errors detected in the compilation of "/qfs/projects/eagles/litz372/mam4xx/src/mam4xx/aero_modes.cpp".```

**Comment by jaelynlitz** [comment]
Build works and all tests on pass w/ CPU build (gcc11.2.0 + cuda11.7). Will ask RC team about the error above for GPU build. (clarification: haero builds with gcc11.2.0 + cuda11.7 then mam4xx throws the above error when trying to compile).

Not using CI to test yet bc the current haero build works, so I don't want to rebuild and break CI until I've figured out what to do.

**Comment by jaelynlitz** [comment]
As one possible path forward, a GPU build with gcc12.2.0 + cuda12.3 compiles w/ haero and mam4xx. There are only two test failures with this build:

```
5607 test 244                                                                        
5608       Start 244: wetdep_validation_local_precip_production                      
5609                                                                                 
5610 244: Test command: /qfs/projects/eagles/litz372/mam4xx/build3/src/validation/wetdep/wetdep_driver "/qfs/projects/eagles/litz372/mam4xx/src/validation/mam_x_validation/wetdep/local_precip_production_input_ts_355.yaml"
5611 244: Working Directory: /qfs/projects/eagles/litz372/mam4xx/build3/src/validation/wetdep
5612 244: Test timeout computed to be: 1500                                          
5613 244: /qfs/projects/eagles/litz372/mam4xx/build3/src/validation/wetdep/wetdep_driver: reading /qfs/projects/eagles/litz372/mam4xx/src/validation/mam_x_validation/wetdep/local_precip_production_input_ts_355.yaml
5614 39/52 Test #244: wetdep_validation_local_precip_production ...........***Exception: Numerical  0.80 sec
5615 test 245                                                                        
5616       Start 245: wetdep_compare_local_precip_production_output                  
5617                                                                                 
5618 245: Test command: /share/apps/python/3.7.0/bin/python3 "/qfs/projects/eagles/litz372/mam4xx/src/validation/mam_x_validation/scripts/compare_mam4xx_mam4.py" "mam4xx_local_precip_production_input_ts_355" "local_precip_production_output_ts_355_ref"
5619 245: Working Directory: /qfs/projects/eagles/litz372/mam4xx/build3/src/validation/wetdep
5620 245: Test timeout computed to be: 1500                                          
5621 245: Traceback (most recent call last):                                         
5622 245:   File "/qfs/projects/eagles/litz372/mam4xx/src/validation/mam_x_validation/scripts/compare_mam4xx_mam4.py", line 32, in <module>
5623 245:     data1 = importlib.import_module(sys.argv[1].replace('.py', ''))        
5624 245:   File "/share/apps/python/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
5625 245:     return _bootstrap._gcd_import(name[level:], package, level)            
5626 245:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import          
5627 245:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load        
5628 245:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
5629 245: ModuleNotFoundError: No module named 'mam4xx_local_precip_production_input_ts_355'
5630 40/52 Test #245: wetdep_compare_local_precip_production_output .......***Failed    0.20 sec
```

I haven't seen a "Numerical" exception before so I'd have to take a closer look.

Is this build a satisfactory path forward? (and running pipelines on a100s instead of p100s)
